// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/catherine-vo/EditorialLight.tsx": () => import("../components/mockups/catherine-vo/EditorialLight.tsx"),
  "./components/mockups/catherine-vo/LandingPage.tsx": () => import("../components/mockups/catherine-vo/LandingPage.tsx"),
  "./components/mockups/catherine-vo/StructuredAuthority.tsx": () => import("../components/mockups/catherine-vo/StructuredAuthority.tsx"),
  "./components/mockups/catherine-vo/StructuredExecutive.tsx": () => import("../components/mockups/catherine-vo/StructuredExecutive.tsx"),
  "./components/mockups/catherine-vo/StructuredIndigo.tsx": () => import("../components/mockups/catherine-vo/StructuredIndigo.tsx"),
  "./components/mockups/catherine-vo/StructuredNavy.tsx": () => import("../components/mockups/catherine-vo/StructuredNavy.tsx"),
  "./components/mockups/catherine-vo/StructuredSage.tsx": () => import("../components/mockups/catherine-vo/StructuredSage.tsx"),
  "./components/mockups/catherine-vo/WarmForest.tsx": () => import("../components/mockups/catherine-vo/WarmForest.tsx"),
  "./components/mockups/catherine-vo/WarmGold.tsx": () => import("../components/mockups/catherine-vo/WarmGold.tsx"),
  "./components/mockups/catherine-vo/WarmPlum.tsx": () => import("../components/mockups/catherine-vo/WarmPlum.tsx"),
  "./components/mockups/catherine-vo/WarmTactile.tsx": () => import("../components/mockups/catherine-vo/WarmTactile.tsx")
};
